# Generated by Django 5.0.6 on 2024-06-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntitiesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=255)),
                ('artist_role', models.CharField(max_length=255)),
                ('program_name', models.CharField(max_length=255)),
                ('composer', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('tickets_info', models.TextField()),
            ],
        ),
    ]
