# Generated by Django 5.0.6 on 2024-06-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symphony_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitiesmaster',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
